### ISSUE TITLE
targetFrameworkSource.split is not a function

### ISSUE THREAD

**Issue by dave0783** [snyk/snyk-nuget-plugin#141]
* `node -v`: v20.3.0
* `npm -v`: 9.6.7
* `snyk -v`: 1.1183.0
* Command run: `snyk monitor --all-projects`

https://github.com/snyk/snyk-nuget-plugin/blob/f433837303b7fedb769e46a12dcb81e4d362d34f/lib/nuget-parser/csproj-parser.ts#L44

When running monitor I am getting `targetFrameworkSource.split is not a function`.  

our .csproj files looks something like:
```
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\build\common.props" />
  <PropertyGroup>
    <TargetFrameworks Condition=" '$([MSBuild]::IsOsPlatform(Windows))' == 'true' ">netstandard1.1;netstandard2.1;net451</TargetFrameworks>
    <TargetFrameworks Condition=" '$([MSBuild]::IsOsPlatform(Windows))' == 'false' ">netstandard1.1;netstandard2.1</TargetFrameworks>
    <DebugType>portable</DebugType>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
</Project>
```

**Comment by dave0783** [comment]
Any updates on this?

**Comment by Aandree5** [comment]
I was getting the same issue and was able to find a workaround.
I had two `<TargetFrameworks>...</TargetFrameworks>` lines, and one of them had a condition `<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net7.0-windows10.0.19041.0</TargetFrameworks>`, by removing the condition it started working without any errors.

I'm not sure but the issue might be in `lib/nuget-parser/csproj-parser.ts` where `propertyGroup?.TargetFrameworks?.[0]` appears to be reading only the first value of `TargetFrameworks` which I would guess it's the condition (which is not a string probably).

**Comment by dotkas** [comment]
@dave0783 @Aandree5 could you try running this with our new beta solution? `snyk test --dotnet-runtime-resolution` and see if this gives you better results?
