### ISSUE TITLE
project name inconsistent

### ISSUE THREAD

**Issue by aryehbeitz** [snyk/snyk-nuget-plugin#24]
When I run `snyk test` on multiple `dotnetcore` projects, if I specify a folder for each project, it takes that as project name.
However, if I specify `.` as in `snyk test .`, the project name is `.` instead of the name of the current folder

example:
```
snyk test .
Testing ....
✗ Medium severity vulnerability found on jQuery@1.10.2
- desc: Cross-site Scripting (XSS)
- info: https://snyk.io/vuln/SNYK-DOTNET-JQUERY-60118
- from: .@1.0.0 > jQuery@1.10.2

...

Organisation: aryehbeitz-btr
Package manager: nuget
Target file: obj/project.assets.json
Open source: no

Tested 334 dependencies for known vulnerabilities, found 11 vulnerabilities, 12 vulnerable paths.
```

As a solution, I would run `pwd` on the current folder and take the last entry as the project name

**Comment by lili2311** [comment]
@aryehbeitz 👋 Is this till an issue for you? We have made many improvements since then :)

**Comment by lili2311** [comment]
Closing this issue, please re-open if there is anything we can help with.
