### ISSUE TITLE
Ideas for improvement

### ISSUE THREAD

**Issue by adrukh** [snyk/snyk-nuget-plugin#44]
Opening this issue mainly to discuss our approach to scanning and protecting .NET projects with Snyk.

Will post comments and invite guests as we go :)

**Comment by adrukh** [comment]
:wave: @MeikTranel

I took the liberty to pull you in here after seeing your remarkable offer to help on https://www.reddit.com/r/dotnet/comments/a1ahrf/offering_my_help_migrating_your_projects_to_net/

We can definitely benefit from speaking to experts in this domain, I was wondering if you could spare some of your time for us :)

**Comment by MeikTranel** [comment]
Hey @adrukh, yer got me :smile: 

I am currently organizing myself to better track the efforts - can i ask you to create a Help Request issue in https://github.com/MeikTranel/MigrationSupport ? I added an issue template for this specific purpose.

**Comment by adrukh** [comment]
:))) Definitely!

I will say that we don't require help migrating any specific project, just seeking (paid!) consultation on .NET internals that seem to overlap *a lot* with your knowledge.

I will try to explain this on an issue as you asked.

**Comment by MeikTranel** [comment]
Oh wait... i see - this is different... You're not searching for MSBuild / NuGet advice, right? Let's discuss this here actually. How can i help you?

**Comment by adrukh** [comment]
Too late - I already opened https://github.com/MeikTranel/MigrationSupport/issues/2 :))

Feel free to close if this is not appropriate. I'd like to move this to a private comm channel, can you please email support@snyk.io?
