### ISSUE TITLE
No support for Roll-forward of packages for security

### ISSUE THREAD

**Issue by JimWolff** [snyk/snyk-nuget-plugin#63]
First, Snyk is the best thing since sliced 🍞, we use it via third party plugin: [azure-pipelines-snyk-task](https://github.com/jessehouwing/azure-pipelines-snyk-task/wiki) making it very easy.

Working with .net core 2.x and interested in security you might enable features in your build (.csproj) that uses `<TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>`
or in the new .net core 3.0 you have a similar feature but it allows more granular control of roll forward policy with options like: `LatestPatch,Minor,Major,LatestMinor,LatestMajor,Disable`
More information here on: [.NET Core runtime roll-forward policy update](https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0/)

This effectively means that the static checking snyk does against a file like `packages.config`,`project.json` or `project.assets.json` becomes inaccurate, since these features allow Nuget Restore to actually restore different versions of a package (where security issues might be fixed)

Scanning the actual files for their versions could be a solution but a somewhat bad one, since checking a dependency file is a lot more simple.

So the only real solution i see is to provide snyk with the extra information that rollup to newest patch version is allowed, unfortunatly that cant just be done on the client side, since you have to either check nuget.org or snyk.io database for information about new patch versions of a certain dependency.

If this was implemented it would be possible to have nightly builds that snyk monitors and warn about new vunerabilities showing up in the snyk.io database, but also automate patching of these vurnerabilities with rollup enabled, today even with rollup enabled snyk just keeps saying you have vurnerabilities.

**Comment by JimWolff** [comment]
Seems like #18 could be related to a solution, scanning the files might be possible if snyk is run in the build pipeline after restore. However it would still require looking at the actual file version not what is in the project reference or project.assets.json file.

**Comment by lili2311** [comment]
hi @JimWolff are you seeing an issue with dependency versions picked up when scanning projects locally?

I do not expect to see processing `projects.assets.json` to yield bad results as it is a build artifact, but for the others we scan those & then look in the packages folder for what is installed. Would be good to have more information from you so we can look into improving this.

**Comment by JimWolff** [comment]
Hi @lili2311 , i'll do a bit more testing to provide you with more detailed information.
