### ISSUE TITLE
packages.lock.json

### ISSUE THREAD

**Issue by nrodrigues1** [snyk/snyk-nuget-plugin#74]
Hi,

We would like to know if you will be interested in supporting "packages.lock.json" feature in NuGet?

https://devblogs.microsoft.com/nuget/enable-repeatable-package-restores-using-a-lock-file/

It could help us automatize our release by using the commited "packages.lock.json" files! 

If you are interested, we will be willing to code it.

Thanks!

**Comment by mweinand** [comment]
We're interested in this!
